<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;

/**
 * @OA\Schema(
 *     schema="Article",
 *     type="object",
 *     title="Article",
 *     description="Article model",
 *     required={"title", "url"},
 *
 *     @OA\Property(property="id", type="integer", readOnly=true, description="The unique identifier of the article"),
 *     @OA\Property(property="hash", type="string", description="a unique hash is generated by the system for each article"),
 *     @OA\Property(property="title", type="string", description="The title of the article"),
 *     @OA\Property(property="url", type="string", description="The URL of the article"),
 *     @OA\Property(property="description", type="string", description="The brief description or excerpt of the article"),
 *     @OA\Property(property="created_at", type="string", format="date-time", readOnly=true, description="The creation timestamp of the article"),
 *     @OA\Property(property="updated_at", type="string", format="date-time", readOnly=true, description="The update timestamp of the article")
 * )
 */
class Article extends Model
{
    use HasFactory;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'hash',
        'title',
        'url',
        'description',
    ];

    /**
     * Get the attributes associated with the article.
     */
    public function attributes(): HasMany
    {
        return $this->hasMany(Attribute::class);
    }
}
